// Layout and colors CONSTANTS
export const LIGHT_THEME = 'LIGHT_THEME';
export const DARK_THEME = 'DARK_THEME';
export const THEME_COLOR = 'THEME_COLOR';
export const NAVBAR_BG = 'NAVBAR_BG';
export const SIDEBAR_BG = 'SIDEBAR_BG';
export const DIRECTION = 'DIRECTION';
export const BLUE_THEME = 'BLUE_THEME';
export const GREEN_THEME = 'GREEN_THEME';
export const RED_THEME = 'RED_THEME';
export const BLACK_THEME = 'BLACK_THEME';
export const PURPLE_THEME = 'PURPLE_THEME';
export const INDIGO_THEME = 'INDIGO_THEME';
export const ORANGE_THEME = 'ORANGE_THEME';
// CHAT CONSTANTS
export const FETCH_CHAT_SUCCESS = 'FETCH_CHAT_SUCCESS';
export const SELECTED_CHAT = 'SELECTED_CHAT';
export const SEARCH_USER = 'SEARCH_USER';
export const MSG_SUBMIT = 'MSG_SUBMIT';

// NOTES CONSTANTS
export const SELECTED_NOTES = 'SELECTED_NOTES';
export const SEARCH_NOTES = 'SEARCH_NOTES';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const ADD_NOTE = 'ADD_NOTE';
export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS';

// EMAIL CONSTANTS
export const STAR_EMAIL = 'STAR_EMAIL';
export const IMPORTANT_EMAIL = 'IMPORTANT_EMAIL';
export const OPEN_EMAIL = 'OPEN_EMAIL';
export const TRASH_EMAIL = 'TRASH_EMAIL';
export const ASSIGN_FOLDER = 'ASSIGN_FOLDER';
export const ASSIGN_LABEL = 'ASSIGN_LABEL';
export const SET_SELECTED_EMAIL = 'SET_SELECTED_EMAIL';
export const FILTER_EMAIL = 'FILTER_EMAIL';
export const SET_EMAIL_VISIBILITY_FILTER = 'SET_EMAIL_VISIBILITY_FILTER';

// STUDENT CONSTANTS
export const SELECTED_STUDENTS = 'SELECTED_STUDENTS';
export const CLEAR_STUDENT = 'CLEAR_STUDENT';
export const SEARCH_STUDENTS = 'SEARCH_STUDENTS';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const ADD_STUDENT = 'ADD_STUDENT';
export const FETCH_STUDENTS = 'FETCH_STUDENTS';

// TEACHERS CONSTANTS
export const SELECTED_TEACHERS = 'SELECTED_TEACHERS';
export const SEARCH_TEACHERS = 'SEARCH_TEACHERS';
export const UPDATE_TEACHER = 'UPDATE_TEACHER';
export const DELETE_TEACHER = 'DELETE_TEACHER';
export const ADD_TEACHER = 'ADD_TEACHER';
export const FETCH_TEACHERS_SUCCESS = 'FETCH_TEACHERS_SUCCESS';

// CLASSES CONSTANTS
export const SELECTED_CLASSES = 'SELECTED_CLASSES';
export const SEARCH_CLASSES = 'SEARCH_CLASSES';
export const UPDATE_CLASS = 'UPDATE_CLASS';
export const DELETE_CLASS = 'DELETE_CLASS';
export const ADD_CLASS = 'ADD_CLASS';
export const FETCH_CLASSES_SUCCESS = 'FETCH_CLASSES_SUCCESS';

// GRADES CONSTANTS
export const SELECTED_GRADES = 'SELECTED_GRADES';
export const SEARCH_GRADES = 'SEARCH_GRADES';
export const UPDATE_GRADE = 'UPDATE_GRADE';
export const DELETE_GRADE = 'DELETE_GRADE';
export const ADD_GRADE = 'ADD_GRADE';
export const FETCH_GRADES_SUCCESS = 'FETCH_GRADES_SUCCESS';

// ACTIVITIES CONSTANTS
export const SELECTED_ACTIVITIES = 'SELECTED_ACTIVITIES';
export const SEARCH_ACTIVITIES = 'SEARCH_ACTIVITIES';
export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const FETCH_ACTIVITIES_SUCCESS = 'FETCH_ACTIVITIES_SUCCESS';

// LICENSES CONSTANTS
export const SELECTED_LICENSES = 'SELECTED_LICENSES';
export const SEARCH_LICENSES = 'SEARCH_LICENSES';
export const UPDATE_LICENSE = 'UPDATE_LICENSE';
export const DELETE_LICENSE = 'DELETE_LICENSE';
export const ADD_LICENSE = 'ADD_LICENSE';
export const FETCH_LICENSES_SUCCESS = 'FETCH_LICENSES_SUCCESS';

// ATTENDANCES CONSTANTS
export const SELECTED_ATTENDANCES = 'SELECTED_ATTENDANCES';
export const SEARCH_ATTENDANCES = 'SEARCH_ATTENDANCES';
export const UPDATE_ATTENDANCE = 'UPDATE_ATTENDANCE';
export const DELETE_ATTENDANCE = 'DELETE_ATTENDANCE';
export const ADD_ATTENDANCE = 'ADD_ATTENDANCE';
export const FETCH_ATTENDANCES_SUCCESS = 'FETCH_ATTENDANCES_SUCCESS';

// NOTICES CONSTANTS
export const SELECTED_NOTICES = 'SELECTED_NOTICES';
export const SEARCH_NOTICES = 'SEARCH_NOTICES';
export const UPDATE_NOTICE = 'UPDATE_NOTICE';
export const DELETE_NOTICE = 'DELETE_NOTICE';
export const ADD_NOTICE = 'ADD_NOTICE';
export const FETCH_NOTICES_SUCCESS = 'FETCH_NOTICES_SUCCESS';
